MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://VGGImageNetPretrained/JCJOHNS/VGG-16"
  BACKBONE:
    CONV_BODY: "VGG16-OICR"
  WSOD_ON: True
  FASTER_RCNN: True
  ROI_HEADS:
    SCORE_THRESH: 0.0
    NMS: 0.3
  ROI_BOX_HEAD:
    NUM_CLASSES: 29
    POOLER_METHOD: "ROIPool"
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.125,)
    FEATURE_EXTRACTOR: "VGG16.roi_head"
  ROI_WEAK_HEAD:
    PREDICTOR: "MISTPredictor"
    LOSS: "RoIRegLoss"
    OICR_P: 0.15
    PARTIAL_LABELS: 'none'
    REGRESS_ON: True
DB:
  METHOD: 'concrete'
DATASETS:
  TRAIN: ("aihub_train",)
  TEST: ("aihub_test",)
DATALOADER:
  NUM_WORKERS : 2
  SIZE_DIVISIBILITY: 32
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 2000
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00025
  STEPS: (20000, 26700)
  MAX_ITER: 50000
SOLVER_CDB:
  BASE_LR: 0.0001
  GAMMA: 3.0
  WEIGHT_DECAY: 0.0001
  STEPS: (20000, 26700)
TEST:
  BBOX_AUG:
    ENABLED: True
    HEUR: "AVG"
    H_FLIP: True
    SCALES: (640, 672, 704, 736, 768, 800)
    MAX_SIZE: 2000
    SCALE_H_FLIP: True